In [222]:
import pandas as pd
import numpy as np
import json

In [223]:
# load the collected datapoints json files for each pose
df_downwarddog = pd.read_json('yoga-dataset/collected-datapoints/downwarddog_data.json')
df_mountain = pd.read_json('yoga-dataset/collected-datapoints/mountain_data.json')
df_tree = pd.read_json('yoga-dataset/collected-datapoints/tree_data.json')
# df_warrior1 = pd.read_json('yoga-dataset/collected-datapoints/warrior1_data.json')
df_warrior2 = pd.read_json('yoga-dataset/collected-datapoints/warrior2_data.json')

# loading additional collected data
df_downwarddog_2 = pd.read_json('yoga-dataset/collected-datapoints/downwarddog-2_data.json')
df_warrior2_2 = pd.read_json('yoga-dataset/collected-datapoints/warrior2-2_data.json')
df_tree_2 = pd.read_json('yoga-dataset/collected-datapoints/tree-2_data.json')
df_goddess = pd.read_json('yoga-dataset/collected-datapoints/goddess_data.json')

In [224]:
#df_downwarddog
# downwarddog_list = []
# for i in range(0,len(dfs)):
#     downwarddog_list.append('Downward Dog')

In [225]:
# df_downwarddog_2

In [226]:
# df_mountain

In [227]:
# df_tree

In [228]:
# df_tree_2

In [229]:
# df_goddess

In [230]:
# df_warrior2

In [231]:
# df_warrior2_2

In [232]:
# transpose the dataframes, then concat and then change the labels on the rows
dfs = [df_downwarddog, df_downwarddog_2, df_mountain, df_tree, df_tree_2, df_goddess, df_warrior2, df_warrior2_2]
idx = 0;
for i in range(len(dfs)):
    dfs[i] = dfs[i].transpose()
    idx += len(dfs[i])

In [233]:
# of data
idx

985

In [234]:
rows_list = []
for i in range(0, idx):
    rows_list.append(i)

In [235]:
# rows_list

In [236]:
yoga_df = pd.concat(dfs)

In [237]:
yoga_df

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,37.320096,319.524752,635.553449,537.640177,288.360819,134.550553,291.000369,162.335143,287.806933,133.936364,...,49.146391,512.685395,248.167919,132.651804,241.194940,133.189674,64.202487,337.985051,64.279785,336.716698
1,295.286053,239.445449,223.751653,282.698466,356.084288,77.159201,354.656113,84.778089,388.905148,136.982422,...,315.522214,114.773700,368.067432,88.688233,479.274304,195.352512,587.830131,301.601069,180.989824,300.660453
2,-23.097323,301.375813,-20.470403,356.379955,-20.381945,356.914822,310.087321,214.844757,387.291198,244.863167,...,384.969297,262.258367,339.136103,243.612825,339.842040,244.392213,318.406512,261.828756,319.746930,260.682758
3,284.030125,280.339137,643.599906,532.447752,408.632850,136.380658,358.348811,131.006125,392.792551,121.037151,...,563.471243,508.355499,390.402861,146.470012,397.800948,145.051830,592.734223,330.523354,586.470924,332.648802
4,264.544473,314.601509,247.634287,327.199242,-12.923662,171.837894,332.151135,130.298023,359.859671,171.431443,...,359.769919,212.558784,340.785734,174.621706,339.674884,175.513740,464.082715,338.228090,459.439066,337.923114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,264.289313,258.306253,268.597721,249.893718,264.735625,253.083734,276.321285,252.993829,265.775227,259.570464,...,302.801290,308.603516,317.078634,337.504294,323.198185,340.634462,362.919048,387.275087,368.603858,387.555554
176,274.990785,85.454881,292.350780,73.905215,277.001136,71.958863,326.420575,83.796681,279.135457,84.049808,...,293.494498,265.650801,210.158264,307.353250,190.137878,303.216576,178.155038,414.401903,178.609994,423.984033
177,212.949314,300.134287,217.132022,293.385366,215.704075,293.445214,218.867833,296.080641,225.327072,297.844191,...,234.031569,357.821316,247.814875,375.504241,248.505517,378.786821,265.659332,390.824568,246.407618,374.380358
178,280.141583,138.403453,291.673874,133.374479,279.440661,127.957445,300.960318,130.099518,286.988426,134.390332,...,311.395059,274.419306,229.593891,330.896006,234.878177,333.630077,246.321285,414.661471,246.809681,413.450458
179,357.377227,132.034252,260.143843,288.344936,350.846493,124.001835,328.221326,129.080131,344.641180,132.362027,...,361.475749,302.332540,249.802959,377.591386,454.740128,331.544983,437.429437,422.083878,435.417224,424.428084

In [286]:
class_names = ['downward dog', 'mountain', 'tree', 'goddess', 'warrior2']
pose_list = []
for i in range(0,len(dfs[0])+len(dfs[1])):
    pose_list.append('Downward Dog')
for i in range(0,len(dfs[2])):
    pose_list.append('Mountain')
for i in range(0,len(dfs[3])+len(dfs[4])):
    pose_list.append('Tree')
for i in range(0,len(dfs[5])):
    pose_list.append('Goddess')
for i in range(0,len(dfs[6])+len(dfs[7])):
    pose_list.append('Warrior2')
    
#yoga_df['Pose'] = pose_list
save_df = yoga_df.copy()
save_df['Pose'] = pose_list
# save_df
save_df.to_json("data.json")

In [239]:
labels = []
for i in range(0,len(dfs[0])+len(dfs[1])):
    labels.append(0)
for i in range(0,len(dfs[2])):
    labels.append(1)
for i in range(0,len(dfs[3])+len(dfs[4])):
    labels.append(2)
for i in range(0,len(dfs[5])):
    labels.append(3)
for i in range(0,len(dfs[6])+len(dfs[7])):
    labels.append(4)

In [240]:
labels = np.array(labels)

In [241]:
type(labels)

numpy.ndarray

In [242]:
len(labels)

985

In [243]:
# change the rows so that the poses have pose starting from pose0 -> ...
yoga_df.index = rows_list

In [244]:
yoga_df

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,37.320096,319.524752,635.553449,537.640177,288.360819,134.550553,291.000369,162.335143,287.806933,133.936364,...,49.146391,512.685395,248.167919,132.651804,241.194940,133.189674,64.202487,337.985051,64.279785,336.716698
1,295.286053,239.445449,223.751653,282.698466,356.084288,77.159201,354.656113,84.778089,388.905148,136.982422,...,315.522214,114.773700,368.067432,88.688233,479.274304,195.352512,587.830131,301.601069,180.989824,300.660453
2,-23.097323,301.375813,-20.470403,356.379955,-20.381945,356.914822,310.087321,214.844757,387.291198,244.863167,...,384.969297,262.258367,339.136103,243.612825,339.842040,244.392213,318.406512,261.828756,319.746930,260.682758
3,284.030125,280.339137,643.599906,532.447752,408.632850,136.380658,358.348811,131.006125,392.792551,121.037151,...,563.471243,508.355499,390.402861,146.470012,397.800948,145.051830,592.734223,330.523354,586.470924,332.648802
4,264.544473,314.601509,247.634287,327.199242,-12.923662,171.837894,332.151135,130.298023,359.859671,171.431443,...,359.769919,212.558784,340.785734,174.621706,339.674884,175.513740,464.082715,338.228090,459.439066,337.923114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,264.289313,258.306253,268.597721,249.893718,264.735625,253.083734,276.321285,252.993829,265.775227,259.570464,...,302.801290,308.603516,317.078634,337.504294,323.198185,340.634462,362.919048,387.275087,368.603858,387.555554
981,274.990785,85.454881,292.350780,73.905215,277.001136,71.958863,326.420575,83.796681,279.135457,84.049808,...,293.494498,265.650801,210.158264,307.353250,190.137878,303.216576,178.155038,414.401903,178.609994,423.984033
982,212.949314,300.134287,217.132022,293.385366,215.704075,293.445214,218.867833,296.080641,225.327072,297.844191,...,234.031569,357.821316,247.814875,375.504241,248.505517,378.786821,265.659332,390.824568,246.407618,374.380358
983,280.141583,138.403453,291.673874,133.374479,279.440661,127.957445,300.960318,130.099518,286.988426,134.390332,...,311.395059,274.419306,229.593891,330.896006,234.878177,333.630077,246.321285,414.661471,246.809681,413.450458
984,357.377227,132.034252,260.143843,288.344936,350.846493,124.001835,328.221326,129.080131,344.641180,132.362027,...,361.475749,302.332540,249.802959,377.591386,454.740128,331.544983,437.429437,422.083878,435.417224,424.428084

In [245]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [246]:
# add better labels to the columns for joint part
col_list = ['nose_x', 'nose_y', 'leftEye_x', 'leftEye_y', 'rightEye_x', 'rightEye_y', 'leftEar_x', 'leftEar_y', 
            'rightEar_x', 'rightEar_y', 'leftShoulder_x', 'leftShoulder_y', 'rightShoulder_x', 'rightShoulder_y', 
            'leftElbow_x', 'leftElbow_y', 'rightElbow_x', 'rightElbow_y', 'leftWrist_x', 'leftWrist_y', 
            'rightWrist_x', 'rightWrist_y', 'leftHip_x', 'leftHip_y', 'rightHip_x', 'rightHip_y', 'leftKnee_x', 
            'leftKnee_y', 'rightKnee_x', 'rightKnee_y', 'leftAnkle_x', 'leftAnkle_y', 'rightAnkle_x', 'rightAnkle_y']
print(len(col_list))

34

In [247]:
yoga_df.columns = col_list

In [248]:
yoga_df

,nose_x,nose_y,leftEye_x,leftEye_y,rightEye_x,rightEye_y,leftEar_x,leftEar_y,rightEar_x,rightEar_y,...,rightHip_x,rightHip_y,leftKnee_x,leftKnee_y,rightKnee_x,rightKnee_y,leftAnkle_x,leftAnkle_y,rightAnkle_x,rightAnkle_y
0,37.320096,319.524752,635.553449,537.640177,288.360819,134.550553,291.000369,162.335143,287.806933,133.936364,...,49.146391,512.685395,248.167919,132.651804,241.194940,133.189674,64.202487,337.985051,64.279785,336.716698
1,295.286053,239.445449,223.751653,282.698466,356.084288,77.159201,354.656113,84.778089,388.905148,136.982422,...,315.522214,114.773700,368.067432,88.688233,479.274304,195.352512,587.830131,301.601069,180.989824,300.660453
2,-23.097323,301.375813,-20.470403,356.379955,-20.381945,356.914822,310.087321,214.844757,387.291198,244.863167,...,384.969297,262.258367,339.136103,243.612825,339.842040,244.392213,318.406512,261.828756,319.746930,260.682758
3,284.030125,280.339137,643.599906,532.447752,408.632850,136.380658,358.348811,131.006125,392.792551,121.037151,...,563.471243,508.355499,390.402861,146.470012,397.800948,145.051830,592.734223,330.523354,586.470924,332.648802
4,264.544473,314.601509,247.634287,327.199242,-12.923662,171.837894,332.151135,130.298023,359.859671,171.431443,...,359.769919,212.558784,340.785734,174.621706,339.674884,175.513740,464.082715,338.228090,459.439066,337.923114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,264.289313,258.306253,268.597721,249.893718,264.735625,253.083734,276.321285,252.993829,265.775227,259.570464,...,302.801290,308.603516,317.078634,337.504294,323.198185,340.634462,362.919048,387.275087,368.603858,387.555554
981,274.990785,85.454881,292.350780,73.905215,277.001136,71.958863,326.420575,83.796681,279.135457,84.049808,...,293.494498,265.650801,210.158264,307.353250,190.137878,303.216576,178.155038,414.401903,178.609994,423.984033
982,212.949314,300.134287,217.132022,293.385366,215.704075,293.445214,218.867833,296.080641,225.327072,297.844191,...,234.031569,357.821316,247.814875,375.504241,248.505517,378.786821,265.659332,390.824568,246.407618,374.380358
983,280.141583,138.403453,291.673874,133.374479,279.440661,127.957445,300.960318,130.099518,286.988426,134.390332,...,311.395059,274.419306,229.593891,330.896006,234.878177,333.630077,246.321285,414.661471,246.809681,413.450458
984,357.377227,132.034252,260.143843,288.344936,350.846493,124.001835,328.221326,129.080131,344.641180,132.362027,...,361.475749,302.332540,249.802959,377.591386,454.740128,331.544983,437.429437,422.083878,435.417224,424.428084

In [249]:
from sklearn.model_selection import train_test_split

In [250]:
features_train, features_test, labels_train, labels_test = train_test_split(yoga_df, labels, test_size=0.35, random_state=42)

In [251]:
# scale the data
from sklearn.preprocessing import MinMaxScaler

In [252]:
scaler = MinMaxScaler()

In [253]:
scaler.fit(features_train)

MinMaxScaler()

In [254]:
features_train = scaler.transform(features_train)

In [255]:
features_test = scaler.transform(features_test)

In [256]:
features_train

array([[0.45233687, 0.56731988, 0.46087208, ..., 0.56833417, 0.27543326,
        0.57336294],
       [0.58931351, 0.86958483, 0.57006109, ..., 0.66630264, 0.18224281,
        0.67526393],
       [0.51261747, 0.35848335, 0.51224471, ..., 0.67843779, 0.49158378,
        0.68312599],
       ...,
       [0.3350187 , 0.42544165, 0.32610543, ..., 0.21153753, 0.28712303,
        0.22662454],
       [0.47605525, 0.46705041, 0.47180857, ..., 0.67511073, 0.48486071,
        0.67889035],
       [0.71040863, 0.91643517, 0.03706213, ..., 0.58032143, 0.21409719,
        0.60483283]])

In [257]:
features_test

array([[0.52200066, 0.48569984, 0.52806841, ..., 0.74311251, 0.51495632,
        0.75098482],
       [0.49793386, 0.33260912, 0.50453954, ..., 0.62602743, 0.48911282,
        0.63400011],
       [0.51546587, 0.58227963, 0.51545278, ..., 0.60953476, 0.36618314,
        0.62512698],
       ...,
       [0.50417069, 0.38834337, 0.50849248, ..., 0.664389  , 0.37370608,
        0.64905768],
       [0.64209862, 0.71073088, 0.68498938, ..., 0.45950835, 0.1800482 ,
        0.50587218],
       [0.51096761, 0.44595581, 0.51788907, ..., 0.6773274 , 0.46412081,
        0.6909293 ]])

In [258]:
labels_train

array([4, 0, 2, 0, 0, 4, 0, 4, 3, 0, 3, 0, 0, 0, 3, 3, 0, 4, 4, 0, 0, 4,
       0, 0, 2, 2, 0, 4, 2, 0, 0, 2, 0, 2, 0, 1, 2, 4, 4, 0, 2, 4, 3, 3,
       4, 1, 0, 3, 4, 4, 3, 1, 2, 3, 2, 2, 2, 0, 3, 2, 4, 3, 1, 0, 0, 2,
       1, 1, 1, 1, 3, 1, 0, 0, 1, 2, 3, 0, 4, 4, 4, 2, 2, 2, 0, 3, 4, 2,
       2, 4, 0, 0, 3, 4, 4, 1, 1, 0, 0, 3, 4, 1, 0, 0, 1, 4, 1, 0, 2, 0,
       1, 4, 4, 4, 2, 4, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 4, 2, 3, 0, 2, 0,
       2, 1, 3, 4, 3, 0, 1, 3, 4, 4, 3, 1, 4, 0, 2, 1, 2, 0, 0, 4, 4, 0,
       2, 4, 3, 2, 1, 0, 0, 1, 4, 1, 2, 0, 0, 0, 1, 4, 4, 1, 2, 2, 4, 0,
       3, 0, 2, 0, 4, 1, 4, 2, 0, 0, 3, 2, 0, 1, 0, 2, 0, 4, 2, 2, 2, 0,
       0, 2, 3, 0, 3, 4, 1, 1, 0, 1, 0, 4, 4, 4, 1, 2, 3, 1, 1, 4, 0, 0,
       4, 0, 1, 4, 0, 2, 1, 2, 1, 0, 4, 4, 4, 1, 2, 3, 0, 0, 0, 4, 4, 3,
       4, 0, 1, 2, 2, 3, 0, 0, 1, 0, 3, 4, 0, 0, 3, 0, 1, 4, 3, 3, 4, 3,
       2, 4, 0, 4, 0, 4, 0, 0, 2, 0, 4, 4, 2, 3, 2, 1, 3, 4, 0, 0, 4, 2,
       4, 1, 0, 0, 4, 1, 2, 4, 4, 3, 3, 0, 4, 4, 2, 4, 4, 2, 4, 0, 3, 0,
       3, 3, 4, 0, 0, 3, 0, 1, 1, 3, 2, 4, 0, 0, 0, 1, 4, 0, 3, 4, 3, 0,
       4, 0, 2, 3, 0, 1, 3, 2, 3, 4, 3, 1, 2, 1, 1, 0, 4, 3, 4, 2, 4, 2,
       0, 0, 3, 4, 4, 3, 1, 2, 1, 0, 0, 4, 2, 0, 4, 0, 2, 1, 1, 1, 0, 0,
       0, 2, 0, 1, 4, 4, 4, 4, 0, 3, 1, 4, 4, 4, 0, 3, 4, 3, 4, 4, 3, 4,
       3, 1, 4, 2, 1, 4, 2, 2, 0, 3, 0, 4, 2, 3, 1, 4, 4, 0, 4, 3, 1, 3,
       1, 4, 3, 1, 0, 3, 3, 3, 1, 1, 1, 0, 4, 4, 2, 1, 2, 3, 4, 4, 4, 2,
       4, 3, 4, 2, 4, 2, 0, 0, 3, 0, 2, 0, 2, 0, 3, 4, 4, 4, 4, 3, 0, 2,
       0, 3, 2, 3, 2, 2, 4, 0, 1, 4, 1, 4, 4, 0, 0, 4, 3, 4, 2, 3, 2, 3,
       3, 0, 4, 3, 2, 1, 2, 0, 0, 4, 0, 0, 0, 4, 0, 2, 4, 1, 1, 1, 3, 1,
       2, 2, 0, 0, 2, 3, 0, 4, 2, 4, 4, 0, 4, 0, 0, 0, 2, 1, 0, 4, 0, 4,
       0, 1, 3, 3, 3, 1, 3, 0, 3, 2, 2, 4, 4, 4, 1, 0, 0, 2, 3, 1, 3, 2,
       4, 4, 0, 2, 1, 0, 4, 4, 2, 0, 0, 0, 4, 2, 2, 2, 1, 0, 1, 4, 2, 1,
       4, 0, 0, 1, 2, 1, 1, 0, 4, 4, 3, 4, 2, 4, 2, 4, 0, 2, 4, 2, 3, 0,
       4, 3, 2, 3, 2, 0, 2, 2, 4, 3, 0, 0, 1, 2, 0, 1, 4, 0, 1, 4, 1, 2,
       1, 4, 1, 3, 0, 3, 4, 0, 1, 0, 2, 1, 0, 2, 0, 2, 0, 3, 0, 0, 1, 4,
       2, 0])

In [259]:
features_train.shape

(640, 34)

In [260]:
features_test.shape

(345, 34)

In [261]:
# do KNN model here and see results
from sklearn.neighbors import KNeighborsClassifier

In [262]:
classifier = KNeighborsClassifier(n_neighbors=15)

In [263]:
classifier.fit(features_train, labels_train)

KNeighborsClassifier(n_neighbors=15)

In [264]:
pred = classifier.predict(features_test)

In [265]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [266]:
# confusion matrix
print(confusion_matrix(labels_test, pred))

[[81  0  0  3  3]
 [ 0 50 12  0  1]
 [ 0  2 73  3  5]
 [ 0  2  8 16 11]
 [ 0  3 20  9 43]]

In [267]:
# classification report
print(classification_report(labels_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        87
           1       0.88      0.79      0.83        63
           2       0.65      0.88      0.74        83
           3       0.52      0.43      0.47        37
           4       0.68      0.57      0.62        75

    accuracy                           0.76       345
   macro avg       0.74      0.72      0.73       345
weighted avg       0.77      0.76      0.76       345

In [268]:
# accuracy_score
print(accuracy_score(labels_test, pred))

0.7623188405797101

In [269]:
# import tensorflow as tf

In [270]:
# print(tf.__version__)

In [271]:
# see results of tensorflow model
# from tensorflow.keras.layers import Input, Dense, Activation, Dropout
# from tensorflow.keras.models import Model

In [272]:
# yoga_df.shape[1]

In [273]:
# input_layer = Input(shape=(yoga_df.shape[1],))

In [274]:
# dense_layer_1 = Dense(15, activation='relu')(input_layer)

In [275]:
# dense_layer_2 = Dense(10, activation='relu')(dense_layer_1)

In [276]:
# output = Dense(5, activation='softmax')(dense_layer_2)

In [277]:
# model = Model(inputs=input_layer, outputs=output)

In [278]:
# model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [279]:
# print(model.summary())

In [280]:
# history = model.fit(features_train,labels_train, batch_size=8,epochs=50,verbose=1,validation_split=0.35)

In [281]:
# score = model.evaluate(features_test, labels_test, verbose=1)

In [282]:
# print("test score: ",  score[0])

In [283]:
# print("test accuracy: ", score[1])